words = [
    "basedpyright",
    "cov",
    "customise",
    "dcc",
    "dccpath",
    "debugpy",
    "idname",
    "mayapy",
    "mobu",
    "mobupy",
    "motionbuilder",
    "ngskintools",
    "noqa",
    "onefile",
    "pipx",
    "programdata",
    "pydantic",
    "pydocstyle",
    "pyinstaller",
    "pyproject",
    "pyright",
    "pytest",
    "pythonunbuffered",
    "scriptplugins",
    "sitecustomize",
    "sitepackages",
    "slf",
    "vcs",
    "venv",
    "wilhelmsen",
]
